### PR TITLE
feat(transactions): adding transactions to the migrations

### PR DESCRIPTION
**Pull request by jpinkster**
Right now if a migration fails it will apply some parts of the migration. Need to add transactions to the process which requires a bit of an overhaul to the structure.

### CODE REVIEW

**Comment by jpinkster** [comment]
Hey @ryd0rz just wanted to check in with you on this change? Let me know when you will get a chance to review. Thanks

**Comment by ryd0rz** [comment]
Looks good.

**Comment by jpinkster** [comment]
Awesome! I look forward to the new published version in npm 🎉

**Comment by ryd0rz** [comment]
yep will get it in there tomorrow... had a rough day apologies for delay.

**Comment by ryd0rz** [comment]
deployed 2.1.0

**Pull request merged**
